server:
  port: 8081
  servlet:
    context-path: "/two"
myName:
  Geekfly
boy:
  age: 18
  name: xiaoming
  content: age is ${girl.age} and name is ${boy.name}
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbgirl?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456a?
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

